# Generated by Django 4.2 on 2023-04-27 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f4bac498-fbf3-4bcc-b0f3-f5142021f913'), primary_key=True, serialize=False),
        ),
    ]
