# Generated by Django 4.2 on 2023-04-27 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('438f0ba3-26cf-4030-a935-71c753d6b756'), primary_key=True, serialize=False),
        ),
    ]
